site_name: CSC Rulebook
site_url: https://csconfederation.github.io/rulebook/
theme: readthedocs
nav:
    - Introduction: 1_introduction.md
    - League Info: 2_league-info.md
    - CSC Conduct Guidelines: 3_csc-conduct-guidelines.md
    - League Processes: 4_league-processes.md
    - Transactions: 5_transactions.md
    - Gameplay Rules: 6_gameplay-rules.md
    - Season Overview: 7_season-overview.md
    - Rules Committee Policies: X_rc-policies.md
    - Appendix: Y_appendix.md
